Websup/urls.py
import Clientapp.views

from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import admin
from django.contrib.auth import views as auth_views

# Websup URL Configuration
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Clientapp
    url(r'^$', login_required(Clientapp.views.dashboard), name="clientapp_dashboard"),
    url(r'^send$', login_required(Clientapp.views.send), name="clientapp_send"),
    url(r'^report$', login_required(Clientapp.views.report), name="clientapp_report"),
    url(r'^contactus$', login_required(Clientapp.views.contactus), name="clientapp_contactus"),

    # Login
    url(r'^user/login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='auth_login'),
    url(r'^user/logout/$', login_required(auth_views.logout), {'template_name': 'registration/logout.html'}, name='auth_logout'),
    url(r'^user/changepassword/$', login_required(auth_views.password_change), {'post_change_redirect': 'password_change_done'}, name='password_change'),
    url(r'^user/passwordchanged/$', login_required(auth_views.password_change_done), name='password_change_done'),

    # Api
    url(r'^admin/whatsapp$', staff_member_required(Clientapp.views.api_mainpage), name='whatsapp_gui'),
    url(r'^admin/whatsapp/(?P<id>[\d]+)/$', staff_member_required(Clientapp.views.api_mainpage), name='whatsapp_gui'),
    url(r'^api/(?P<command>[a-z_]+)/$', staff_member_required(Clientapp.views.api), name="whatsapp_api"),
    url(r'^admin/adminReport$', staff_member_required(Clientapp.views.adminReport), name='whatsapp_report'),

]


if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whatsapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'whatsapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	# url(r'^register/$', views.register, name='signup'),
 #    url(r'^activate/(?P<pk>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
 #        views.activate_new_user, name='activate_user'),
    # url(r'^login/$', views.login,
    #     {'template_name': 'login.html', 'authentication_form': LoginForm, },
    #     name='login'),
    # url(r'^logout/$', a_views.logout, {'next_page': '/login'}),	
	url(r'', include('dashboard.urls')),
    url(r'^admin/', include(admin.site.urls)),

]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.forms import ModelForm , TextInput , Select  , FileInput , ChoiceField
from django.utils.translation import ugettext_lazy as _


class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Plan(models.Model):
	name_of_plan = models.CharField(verbose_name = "Plan name", max_length=50, null=False, blank=False)
	credits = models.IntegerField(verbose_name = "Credits")
	price = models.IntegerField(verbose_name = "Price")
	duration = models.CharField(verbose_name = "Validity", max_length=30, null=False, blank=False)
	description = models.TextField(verbose_name='Description', blank=True)

	def __str__(self):
		return "-".join([self.name_of_plan , str(self.credits) , str(self.price), str(self.duration)])


class User_Plan(models.Model):
	user = models.ForeignKey(MyUser)
	plan = models.ForeignKey(Plan)
	started_on = models.DateField(_("Subscribed On"), auto_now=False , auto_now_add=True)
	paid_amount = models.IntegerField(verbose_name='Paid Amount', default=0)
	total_credits = models.IntegerField(verbose_name='Total Credits')
	used_credits = models.IntegerField(verbose_name='Used Credits')
	remaining_credits = models.IntegerField(verbose_name='Remaining Credits')
	ending_on = models.DateField(_("Valid Upto"), auto_now=False , auto_now_add=True)
	

class Contact(models.Model):
	number = models.IntegerField(verbose_name='Mobile Number' , max_length=20, blank=False, null=False)


class WhatApp_Message_Format(models.Model):
	from_user = models.ForeignKey(MyUser)
	sent_on = models.DateField(_("Sent On"), auto_now=False , auto_now_add=True)
	msg_text = models.CharField(verbose_name='message' , max_length=1500, blank=True, null=True)
	## To implement after django-media setup
	# msg_img1
	# msg_img2
	# msg_img3
	# msg_img4
	# msg_doc

	
class WhatsApp_Bulk_Message(models.Model):
	to_contact = models.ForeignKey(Contact)
	message_format = models.ForeignKey(WhatApp_Message_Format)
	delivered = models.BooleanField(default=False)

Clientapp/views.py
import threading
import re
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from Clientapp.models import *
from Clientapp.forms import *
from Clientapp.yowsup_integration.stack import *

#####################
#   User Views
#####################
def dashboard(request):
    request.user.update_credits()
    plan_details = Whatsapp_Plan.objects.filter(is_active=True)
    user_plan_details = User_Plan.objects.filter(user=request.user).order_by('-id')
    if len(user_plan_details) > 0:
        user_plan_details = user_plan_details[0]
    template = "clientapp/dashboard.html"
    context = {'plan_details': plan_details, 'user_plan_details': user_plan_details}
    return render(request, template, context)


def send(request):
    errors = None
    Text_Formset = forms.formset_factory(Whatsapp_Text_Form, extra=1)
    Image_Formset = forms.formset_factory(Whatsapp_Image_Form, extra=1)
    #vCard_Formset = forms.formset_factory(Whatsapp_vCard_Form, extra=1)

    if (request.method == "POST"):
        message_form = Whatsapp_New_Message_Form(request.POST, request.FILES)
        text_formset = Text_Formset(request.POST, prefix="text")
        image_formset = Image_Formset(request.POST, request.FILES, prefix="image")
     #   vcard_formset = vCard_Formset(request.POST, prefix="vcard")
        mobile_numbers = request.POST["mobile_numbers"]
        mobile_numbers = re.findall('\d{10}', mobile_numbers)
        if len(mobile_numbers) < 1:
            errors = "No Valid Mobile Number Found"
        elif message_form.is_valid() and text_formset.is_valid():
            ##########################################################################
            #   Validate and get proper Mobile numbers
            ##########################################################################
            contacts = []
            for mobile_number in mobile_numbers:
                mobile_number = '91' + mobile_number
                mobile_number_object = Whatsapp_Number.objects.filter(number=mobile_number)
                if len(mobile_number_object) < 1:
                    mobile_number_object = Whatsapp_Number()
                    mobile_number_object.number = mobile_number
                    mobile_number_object.save()
                else:
                    mobile_number_object = mobile_number_object[0]
                contacts.append(mobile_number_object)

            ##########################################################################
            #   Generate Db Objects from formsets using commit=False
            ##########################################################################
            new_message_format = message_form.save(commit=False)
            credits = request.user.remaining_credits
            len_contacts = len(contacts)

            # Saving details for Message_Format
            new_message_format.user = request.user
            new_message_format.save()
            new_message_format.mobile_numbers.add(*contacts)

            # Saving each text message
            for text_form in text_formset:
                text_message = text_form.save(commit=False)
                text_message.format = new_message_format
                if len(text_message.text) > 0:
                    text_message.save()
                    if credits < len_contacts: continue
                    else: credits -= len_contacts
                    for contact in contacts:
                        whatsapp_text_delivery = Text_Delivery()
                        whatsapp_text_delivery.to_number = contact
                        whatsapp_text_delivery.message_text = text_message
                        whatsapp_text_delivery.message_format = new_message_format
                        whatsapp_text_delivery.save()

            # Saving each image message
            for image_form in image_formset:
                image_message = image_form.save(commit=False)
                image_message.format = new_message_format
                if bool(image_message.image):
                    image_message.save()
                    if credits < len_contacts: continue
                    else: credits -= len_contacts
                    for contact in contacts:
                        whatsapp_image_delivery = Image_Delivery()
                        whatsapp_image_delivery.to_number = contact
                        whatsapp_image_delivery.message_image = image_message
                        whatsapp_image_delivery.message_format = new_message_format
                        whatsapp_image_delivery.save()

            # Saving each vcard message
            # for vcard_form in vcard_formset:
            #     vcard_message = vcard_form.save(commit=False)
            #     vcard_message.format = new_message_format
            #     if len(vcard_message.name) > 0:
            #         vcard_message.save()
            #         if credits < len_contacts: continue
            #         else: credits -=  len_contacts
            #         for contact in contacts:
            #             whatsapp_vcard_delivery = vCard_Delivery()
            #             whatsapp_vcard_delivery.to_number = contact
            #             whatsapp_vcard_delivery.message = vcard_message
            #             whatsapp_vcard_delivery.message_format = new_message_format
            #             whatsapp_vcard_delivery.save()

            request.user.update_credits()
            return HttpResponseRedirect("/report")
        else:
            errors = message_form.errors + text_formset.errors

    else:
        message_form = Whatsapp_New_Message_Form()

    text_formset = Text_Formset(prefix="text")
    image_formset = Image_Formset(prefix="image")
    #vcard_formset = vCard_Formset(prefix="vcard")

    template = "clientapp/send.html"
    context = {
        'message_form': message_form,
        'text_formset': text_formset,
        'image_formset': image_formset,
     #   'vcard_formset': vcard_formset,
        'errors': errors
    }
    return render(request, template, context)


def report(request):
    individual_messages = Delivery_Status.objects.all().order_by('-added_on')
    template = "clientapp/report.html"
    context = {'individual_messages': individual_messages}
    return render(request, template, context)


def contactus(request):
    errors = None
    if (request.method == "POST"):
        contact_form = Contactus_Form(request.POST)
        if contact_form.is_valid():
            new_contact = contact_form.save(commit=False)
            new_contact.from_user = request.user
            new_contact.save()
            return HttpResponseRedirect("/")
        else:
            errors = str(contact_form.errors)
    contact_form = Contactus_Form()
    template = "clientapp/contactus.html"
    context = {'contact_form': contact_form, 'errors': errors}
    return render(request, template, context)


def adminReport(request):
    individual_messages = Delivery_Status.objects.all()
    template = "clientapp/adminReport.html"
    context = {'individual_messages': individual_messages}
    return render(request, template, context)


########################################################################################################################
#
#                          Adding  Yowsup   Integration
#
# #######################################################################################################################
yowsup_handler = YowsupWebStack()

# Starting the Whatsapp Stack Loop in a new thread.
threading.Thread(target=yowsup_handler.start).start()

# Access to yowsupweb layer
weblayer = yowsup_handler.get_web_layer()


def api(request, command):
    if (command == 'login'):
        if not weblayer.assertConnected():
            weblayer.login('918200594756', 'Db1rSq/g8EzVgs+LbWp2idQcUUc=')

    elif (command == 'connection_status'):
        return HttpResponse(weblayer.assertConnected())

    elif (command == 'send'):
        id = request.GET.get('id', '')
        if len(id) < 1:
            return HttpResponse(False)
        msg_object = Delivery_Status.objects.filter(id=id, delivery_status=0)
        if (len(msg_object) > 0):
            msg_object = msg_object[0]
            weblayer.send_message(msg_object)
            return HttpResponse(True)

    elif (command == 'status'):
        id = request.GET.get('id', '')
        if len(id) < 1:
            return HttpResponse(False)
        msg_object = Delivery_Status.objects.filter(id=id)
        if (len(msg_object) > 0) and (msg_object[0].delivery_status == 1):
            return HttpResponse(True)
    
    elif (command == 'video'):
        mobilenumber = '919428919278'
        path = "/home/alex/Desktop/ezgif-2-f229160e22.mp4"
        weblayer.media_send(mobilenumber, path, "video" , None)
        return HttpResponse(True)

    # Default Case if nothing else works
    return HttpResponse(False)


def api_mainpage(request, id=None):
    if id is None:
        msg_formats = [i for i in Whatsapp_Message_Format.objects.filter(user__is_active=True) if i.unsent_msg() > 0]
        template = "clientapp/whatsapp_mainpage.html"
        context = {'msg_formats': msg_formats}
        return render(request, template, context)
    else:
        obj = Delivery_Status.objects.filter(message_format__id=id, delivery_status=0)
        if len(obj)>0:
            message_format = obj[0].message_format
        else:
            message_format = None

        contacts = [status.to_number.number for status in obj]
        weblayer.contacts_sync(contacts)
        template = "clientapp/whatsapp_message.html"
        context = {'message_format':message_format,  'messages' : obj}
        return render(request, template, context)

Clientapp/templates/clientapp_aboutus.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

Clientapp/templates/clientapp_contactus.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

Clientapp/templates/clientapp_dashboard.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title></title>
  {% block css %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css' %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/switchery/css/switchery.min.css' %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/multiselect/css/multi-select.css' %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/select2/css/select2.min.css' %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/bootstrap-select/css/bootstrap-select.min.css' %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css' %}"/>
  {% endblock %}
</head>
<body>
<div class="container">
            <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">

            <h4 class="page-title">Dashboard</h4>
        </div>
    </div>
<div class="row">
  <div class="col-md-6 col-lg-3">
      <div class="widget-bg-color-icon card-box">
          <div class="bg-icon bg-icon-info pull-left">
              <i class="md md-attach-money text-info"></i>
          </div>
          <div class="text-right">
              <h3 class="text-dark"><b class="counter">0</b></h3>
              <p class="text-muted">Whatsapp Credtis</p>
          </div>
          <div class="clearfix"></div>
      </div>
  </div>

  <div class="col-md-6 col-lg-3">
      <div class="widget-bg-color-icon card-box">
          <div class="bg-icon bg-icon-custom pull-left">
              <i class="md md-add-shopping-cart text-custom"></i>
          </div>
          <div class="text-right">
              <h3 class="text-dark"><b class="counter">0</b></h3>
              <p class="text-muted">New Mails</p>
          </div>
          <div class="clearfix"></div>
      </div>
  </div>
  
  <div class="col-md-6 col-lg-3">
      <div class="widget-bg-color-icon card-box">
          <div class="bg-icon bg-icon-info pull-left">
              <i class="md md-equalizer text-info"></i>
          </div>
          <div class="text-right">
              <h3 class="text-dark"><b class="counter">0</b>%</h3>
              <p class="text-muted">Register User</p>
          </div>
          <div class="clearfix"></div>
      </div>
  </div>

  <div class="col-md-6 col-lg-3">
      <div class="widget-bg-color-icon card-box">
          <div class="bg-icon bg-icon-custom pull-left">
              <i class="md md-remove-red-eye text-custom"></i>
          </div>
          <div class="text-right">
              <h3 class="text-dark"><b class="counter">64,570</b></h3>
              <p class="text-muted">Current users</p>
          </div>
          <div class="clearfix"></div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <div class="card-box">
      </q><h4 class="text-dark header-title m-t-0">Today's Update</h4>
        <div class="text-center">
            <ul class="list-inline chart-detail-list">
                <li>
                    <h5><i class="fa fa-circle m-r-5" style="color: #7e57c2;"></i>News</h5>
                </li>
                <li>
                    <h5><i class="fa fa-circle m-r-5" style="color: #34d3eb;"></i>Links</h5>
                </li>
            </ul>
        </div>
      <div id="morris-line-example" style="height: 300px;">
    </div>
  </div>
  </div>
  <div class="col-lg-4">
    <div class="card-box">
      <h4 class="text-dark header-title m-t-0 m-b-30">Todays Activity</h4>
      <div class="widget-chart text-center">
            <input class="knob" data-width="150" data-height="150" data-linecap=round data-fgColor="#34d3eb" value="80" data-skin="tron" data-angleOffset="180" data-readOnly=true data-thickness=".15"/>
        <h5 class="text-muted m-t-20">Todays send messages</h5>
        <h2 class="font-600">75</h2>
        <ul class="list-inline m-t-15">
          <li>
            <h5 class="text-muted m-t-20">Total mesage</h5>
            <h4 class="m-b-0">1000</h4>
          </li>
          <li>
            <h5 class="text-muted m-t-20">Last week</h5>
            <h4 class="m-b-0">523</h4>
          </li>
          <li>
            <h5 class="text-muted m-t-20">Last Month</h5>
            <h4 class="m-b-0">965</h4>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- end row -->
</div>
{% endblock %}

{% block javascrpit %}
        <script type="text/javascript" src="{% static 'plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/switchery/js/switchery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/multiselect/js/jquery.multi-select.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/jquery-quicksearch/jquery.quicksearch.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/select2/js/select2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>

        <script type="text/javascript" src="{% static 'plugins/autocomplete/jquery.mockjax.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/autocomplete/jquery.autocomplete.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/autocomplete/countries.js' %}"></script>
        <script type="text/javascript" src="{% static 'pages/autocomplete.js' %}"></script>

        <script type="text/javascript" src="{% static 'pages/jquery.form-advanced.init.js' %}"></script>

{% endblock %}
</body>
</html>

Clientapp/templates/clientapp_plans.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

Clientapp/templates/clientapp_report.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

Clientapp/templates/clientapp_send.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
<html>
	<head>
		<title>Bluk Whatsapp</title>
        <!-- Plugins css-->
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css' %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/switchery/css/switchery.min.css' %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/multiselect/css/multi-select.css'%}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/select2/css/select2.min.css' %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/bootstrap-select/css/bootstrap-select.min.css' %}"/>
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/morris/morris.css' %}"/>
      <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css' %}"/>

        <script type="text/javascript" src="{% static 'js/modernizr.min.js' %}"></script>
        <script src="{% static 'plugins/morris/morris.min.js' %}" ></script>        
        <script src="{% static 'pages/jquery.dashboard.js' %}" ></script>
    </head>
{% endblock head %}

{% block content %}

<div class="container">
            <!-- Page-Title -->
  <div class="row">
    <div class="col-sm-12">
      <div class="card-box">
        <h4 class="m-t-0 header-title"><b>Send whatsapp messages</b></h4>
        <br>
          <div class="row">
            <div class="col-md-8">
              <form method="POST" action="." class="form-horizontal" role="form">  
              {% csrf_token %}
                  <div class="form-group">
                      <lable class="col-md-2 control-label" for="id_campaign_name">Campaign Name</lable>
                      <div class="col-md-6">
                        <input class="form-control" id="id_campaign_name" type="text" maxlength="100" placeholder="Enter Campaign Name here..">
                      </div>                           
                  </div>
                  <div class="form-group">
                      <label class="col-md-2 control-label" for="">Mobile Numbers</label>
                      <div class="col-md-6">
                          <textarea class="form-control" rows="5" id=""></textarea>
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-md-2 control-label">Count</label>
                      <div class="col-md-4">
                          <input type="text" class="form-control" placeholder="total number in list">
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="col-md-2 control-label" for="id_msg_text">Message</label>
                      <div class="col-md-6">
                          <textarea class="form-control" placeholder="Enter your text message" id="id_msg_text" maxlength="1500">
                          </textarea>
                      </div>
                  </div>
              </form>
            </div>
          </div>
      </div>
    </div> 
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="card-box">
        <h4 class="m-t-0 header-title"><b>Upload Image, Videos, PDF</b></h4>
        <div class="row">
          <div class="col-md-6">
            <div class="p-20">
              <form method="POST" action="." class="form-horizontal" role="form">
                <div class="form-group">
                  <label class="control-label">Upload Image 1 </label>
                  <input type="file" class="filestyle" data-buttonbefore="true">
                </div>
                <div class="form-group">
                  <label class="control-label">Upload Image 2 </label>
                  <input type="file" class="filestyle" data-buttonbefore="true">
                </div>
                <div class="form-group">
                  <label class="control-label">Upload Image 3 </label>
                  <input type="file" class="filestyle" data-buttonbefore="true">
                </div>
                <div class="form-group">
                  <label class="control-label">Upload Image 4 </label>
                  <input type="file" class="filestyle" data-buttonbefore="true">
                </div>
              </form>
            </div>
          </div>
          <div class="col-md-6">
            <div class="p-20">
              <form method="POST" action="." class="form-horizontal" role="form">
                <div class="form-group">
                  <label class="control-label">Upload Audio </label>
                  <input type="file" class="filestyle" data-buttonbefore="true">
                </div>
                <div class="form-group">
                  <label class="control-label">Upload Video </label>
                  <input type="file" class="filestyle" data-buttonbefore="true">
                </div>
                <div class="form-group">
                  <label class="control-label">Upload pdf </label>
                  <input type="file" class="filestyle" data-buttonbefore="true">
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="card-box">
        <h4 class="m-t-0 header-title"><b>Create VCard</b></h4>
          <br>
            <div class="row">
              <div class="col-md-6">
                <form class="form-horizontal" role="form">                                    
          <div class="form-group">
              <input type="text" class="form-control" placeholder="Campaign Name">
              <input type="text" class="form-control" placeholder="Adreess">
              <input type="text" class="form-control" placeholder="contact number">
              <input type="text" class="form-control" placeholder="Office numvber">
              <input type="text" class="form-control" placeholder="Cell number">
              <input type="text" class="form-control" placeholder="Email id">
              <input type="text" class="form-control" placeholder="Website URL">
          </div>
          <input class="btn btn-purple waves-effect waves-light" type="submit" value="submit">
      </div>
    </div>
  </div> 
</div>
{% endblock %}
</body>
</html>
{% block script %}
  <script>
      var resizefunc = [];
      function addNewlines(str) {
        var result = '';
        while (str.length > 0) {
          result += str.substring(0, 200) + '\n';
          str = str.substring(200);
        }
        return result;
      }
  </script> 
{% block javascript %}
      <script type="text/javascript" src="{% static 'plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/switchery/js/switchery.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/multiselect/js/jquery.multi-select.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/jquery-quicksearch/jquery.quicksearch.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/select2/js/select2.min.js' %}" ></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>

      <script type="text/javascript" src="{% static 'plugins/autocomplete/jquery.mockjax.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/autocomplete/jquery.autocomplete.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/autocomplete/countries.js' %}"></script>
      <script type="text/javascript" src="{% static 'pages/autocomplete.js' %}"></script>

      <script type="text/javascript" src="{% static 'pages/jquery.form-advanced.init.js' %}"></script>
{% endblock javascript %}

{% endblock %}	
  