Websup/urls.py
import Clientapp.views

from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import admin
from django.contrib.auth import views as auth_views

# Websup URL Configuration
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Clientapp
    url(r'^$', login_required(Clientapp.views.dashboard), name="clientapp_dashboard"),
    url(r'^send$', login_required(Clientapp.views.send), name="clientapp_send"),
    url(r'^report$', login_required(Clientapp.views.report), name="clientapp_report"),
    url(r'^contactus$', login_required(Clientapp.views.contactus), name="clientapp_contactus"),

    # Login
    url(r'^user/login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='auth_login'),
    url(r'^user/logout/$', login_required(auth_views.logout), {'template_name': 'registration/logout.html'}, name='auth_logout'),
    url(r'^user/changepassword/$', login_required(auth_views.password_change), {'post_change_redirect': 'password_change_done'}, name='password_change'),
    url(r'^user/passwordchanged/$', login_required(auth_views.password_change_done), name='password_change_done'),

    # Api
    url(r'^admin/whatsapp$', staff_member_required(Clientapp.views.api_mainpage), name='whatsapp_gui'),
    url(r'^admin/whatsapp/(?P<id>[\d]+)/$', staff_member_required(Clientapp.views.api_mainpage), name='whatsapp_gui'),
    url(r'^api/(?P<command>[a-z_]+)/$', staff_member_required(Clientapp.views.api), name="whatsapp_api"),
    url(r'^admin/adminReport$', staff_member_required(Clientapp.views.adminReport), name='whatsapp_report'),

]


if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^index$', views.index, name='index'),
    url(r'^bulk_whatsapp$', views.bulk_whatsapp, name='bulk_whatsapp'),
]

whatsapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'whatsapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	# url(r'^register/$', views.register, name='signup'),
 #    url(r'^activate/(?P<pk>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
 #        views.activate_new_user, name='activate_user'),
    # url(r'^login/$', views.login,
    #     {'template_name': 'login.html', 'authentication_form': LoginForm, },
    #     name='login'),
    # url(r'^logout/$', a_views.logout, {'next_page': '/login'}),	
	url(r'', include('dashboard.urls')),
    url(r'^admin/', include(admin.site.urls)),

]

Clientapp/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Custom User Manager
class MyUserManager(BaseUserManager):

    def create_user(self, name, email, password=None):
        if not email:
            raise ValueError('User must have an email address')
        if not name:
            raise ValueError('User must have a Name')

        user = self.model(email=self.normalize_email(email))

        user.name = name
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, name, email, password):
        user = self.create_user(name, email, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user

        class Meta:
            model = MyUser
            exclude = ("",)


class MyUser(AbstractBaseUser):
    name = models.CharField(verbose_name='Full Name', max_length=255, unique=False, null=False, blank=False)
    email = models.EmailField(verbose_name='Email Address', max_length=255, unique=True, null=False, blank=False)
    # password is AutoField from AbstractBaseUser
    created_on = models.DateTimeField(verbose_name="Account Created on ", auto_now=False, auto_now_add=True)

    total_credits = models.IntegerField(verbose_name="Total Credits", default=0)
    remaining_credits = models.IntegerField(verbose_name="Remaining Credits", default=0)
    used_credits = models.IntegerField(verbose_name="Used Credits", default=0)
    queued_credits = models.IntegerField(verbose_name="Queued Credits", default=0)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_active

    def update_credits(self):
        # Update Total Credits
        user_plans = User_Plan.objects.filter(user__id=self.id)
        if len(user_plans) > 0:
            self.total_credits = sum([user_plan.plan.credits for user_plan in user_plans])
        else:
            self.total_credits = 0

        # Update Queued Credits
        queued_messages = Delivery_Status.objects.filter(message_format__user=self, delivery_status=0).count()
        self.queued_credits = queued_messages

        # Update Sent Credits
        sent_messages = Delivery_Status.objects.filter(message_format__user=self, delivery_status=1).count()
        self.used_credits = sent_messages

        # Update Remaining Credits
        self.remaining_credits = self.total_credits - self.queued_credits - self.used_credits
        self.save()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = 'Website User'


class Whatsapp_Plan(models.Model):
    name_of_plan = models.CharField(verbose_name="Plan name", max_length=50, null=False, blank=False)
    price = models.IntegerField(verbose_name="Amount Paid")
    credits = models.IntegerField(verbose_name="Offered Credits")
    description = models.TextField(verbose_name='Description', blank=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name_of_plan

    class Meta:
        verbose_name_plural = 'Whatsapp Plan'


class User_Plan(models.Model):
    user = models.ForeignKey(MyUser)
    plan = models.ForeignKey(Whatsapp_Plan)
    paid_amount = models.IntegerField(verbose_name='Paid Amount', default=0)
    started_on = models.DateField(verbose_name="Subscribed On", auto_now=False, auto_now_add=True)

    objects = MyUserManager()

    def save(self, *args, **kwargs):
        super(User_Plan, self).save(*args, **kwargs)
        self.user.update_credits()

    def __str__(self):
        return "-".join([self.user.email, self.plan.name_of_plan])

    class Meta:
        verbose_name_plural = 'User Plan'


class Whatsapp_Credentials(models.Model):
    number = models.CharField(verbose_name='Mobile Number', max_length=12, blank=False, null=False, unique=True)
    password = models.CharField(verbose_name='Password', max_length=70, blank=False, null=False)

    class Meta:
        verbose_name_plural = 'Yowsup Credentials'


class Whatsapp_Number(models.Model):
    number = models.CharField(verbose_name='Mobile Number', max_length=12, blank=False, null=False, unique=True)

    def __str__(self):
        return self.number

    class Meta:
        verbose_name_plural = 'Whatsapp Contact Number'


class Contactus(models.Model):
    name = models.CharField(verbose_name="name", max_length=25, null=False, blank=False)
    contact_number = models.IntegerField(verbose_name="Mobile Number")
    email_address = models.EmailField(verbose_name="Email Address", max_length=255, unique=True, null=False, blank=False)
    text_message = models.CharField(verbose_name="Problem Description", max_length=1500, null=True, blank=False)
    added_on = models.DateTimeField(verbose_name="Added On", auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Contact Us'

    def __str__(self):
        return "-".join([self.name, str(self.added_on)])


class Whatsapp_Message_Format(models.Model):
    format_name = models.CharField(verbose_name="Advertisement Name", max_length=100, null=False, blank=True)
    user = models.ForeignKey(MyUser)
    added_on = models.DateTimeField(verbose_name='Added On', auto_now=False, auto_now_add=True)
    mobile_numbers = models.ManyToManyField(Whatsapp_Number)

    def unsent_msg(self):
        a = Text_Delivery.objects.filter(message_text__format=self, delivery_status=0).count()
        b = Image_Delivery.objects.filter(message_image__format=self, delivery_status=0).count()
        c = vCard_Delivery.objects.filter(message__format=self, delivery_status=0).count()
        return a+b+c
        

    def __str__(self):
        return "-".join([self.user.name, self.format_name])

    class Meta:
        verbose_name_plural = 'Whatsapp Message Formats'


class Whatsapp_vCard(models.Model):
    format = models.ForeignKey(Whatsapp_Message_Format)
    name = models.CharField(verbose_name="vCard Name", max_length=50, blank=False, null=False)
    person_name = models.CharField(verbose_name="Person Name", max_length=150, blank=False, null=False)
    company = models.CharField(verbose_name="Company", max_length=200, blank=True)
    mobile1 = models.CharField(verbose_name="Mobile Number 1", max_length=15, blank=True)
    mobile2 = models.CharField(verbose_name="Mobile Number 2", max_length=15, blank=True)
    mobile3 = models.CharField(verbose_name="Mobile Number 3", max_length=15, blank=True)
    address = models.CharField(verbose_name="Address", max_length=300, blank=True)
    email = models.EmailField(verbose_name="Email", max_length=50, blank=True)
    url = models.URLField(verbose_name="Website", blank=True)

    class Meta:
        verbose_name_plural = 'Whatsapp vCard'


class Whatsapp_Image(models.Model):
    format = models.ForeignKey(Whatsapp_Message_Format)
    image = models.ImageField(upload_to='img', null=True, blank=True)

    def __str__(self):
            return "{0}".format(self.image.url)

    class Meta:
        verbose_name_plural = 'Whatsapp Image'


class Whatsapp_Text(models.Model):
    format = models.ForeignKey(Whatsapp_Message_Format)
    text = models.CharField(verbose_name='Text Content', max_length=1500, blank=True, null=True)

    def __str__(self):
        return "{0}".format(self.text)

    class Meta:
        verbose_name_plural = 'Whatsapp Text'


class Delivery_Status(models.Model):
    to_number = models.ForeignKey(Whatsapp_Number, related_name='to_whatsapp_number')
    message_format = models.ForeignKey(Whatsapp_Message_Format)
    added_on = models.DateTimeField(auto_now_add=True, auto_now=False)
    whatsapp_message_id = models.CharField(verbose_name="Whatsapp generated id", max_length=50, blank=True, null=True)
    delivery_status = models.IntegerField(default=0)
    delivery_time = models.DateTimeField(verbose_name="Delivery Time", auto_now=False, auto_now_add=True, blank=True, null=True)
    sent_using = models.ForeignKey(Whatsapp_Credentials, related_name='sent_using', blank=True, null=True)

    def __str__(self):
        return "{0}-{1}".format( self.to_number.number, self.delivery_status)

    class Meta:
        verbose_name_plural = 'Delivery Status'


class Text_Delivery(Delivery_Status):
    message_text = models.ForeignKey(Whatsapp_Text)

    class Meta:
        verbose_name_plural = 'Delivery Text'


class Image_Delivery(Delivery_Status):
    message_image = models.ForeignKey(Whatsapp_Image)

    class Meta:
        verbose_name_plural = 'Delivery Image'


class vCard_Delivery(Delivery_Status):
    message = models.ForeignKey(Whatsapp_vCard)

    class Meta:
        verbose_name_plural = 'Delivery vCard'

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm, PasswordChangeForm, \
    SetPasswordForm
from django.contrib.auth import get_user_model
from django.contrib.auth import password_validation

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, HTML, Submit
from .models import *

class LoginForm(AuthenticationForm):
    """Form to allow user to log in to system"""
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'name': 'password',
                                          'type': 'password'}))


class SignUpForm(UserCreationForm, PasswordResetForm):
    username = forms.CharField(
        label="Username",
        max_length=30,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'name': 'username'}))
    password1 = forms.CharField(
        label="Password",
        max_length=30, strip=False,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'name': 'password',
                   'type': 'password'}))
    password2 = forms.CharField(
        label="Password confirmation",
        strip=False,
        max_length=30,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'name': 'password confirmation',
                   'type': 'password'}))
    email = forms.CharField(
        label="email address",
        max_length=60,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'name': 'email address'}))

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']


class ChangePassword(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(ChangePassword, self).__init__(*args, **kwargs)
        self.helper = password_change_helper
        self.use_required_attribute = False

    class Meta:
        model = get_user_model()
        fields = ['old_password', 'new_password1', 'new_password2']

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, "index.html")

def bulk_whatsapp(request):
	return render(request, "Bulk_whatsapp.html")

# def register(request):
#     if request.method == "POST":
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             new_user_name = form.cleaned_data['username']
#             new_user_password = form.cleaned_data['password1']
#             new_user_email = form.cleaned_data['email']
#             new_user = User.objects.create_user(username=new_user_name,
#                                                 email=new_user_email,
#                                                 password=new_user_password)
#             new_user.is_active = False
#             new_user.save()
#             new_user_token = activation_user().make_token(new_user)
#             host = request.get_host()

#             send_mail("Activate YOur Account",
#                       loader.render_to_string('user_activate.html',
#                                               {'pk': new_user.id,
#                                                'token': new_user_token,
#                                                'domain': host,
#                                                'user': new_user_name}), 'test.gahan@gmail.com', ['gahan@quixom.com', new_user_email])
#             return HttpResponseRedirect('/login/')
#     else:
#         form = SignUpForm()
#     return render(request, 'registration.html', {'form': form})


# def activate_new_user(request, pk, token):
#     usr = User.objects.get(pk=pk)
#     verified = activation_user().check_token(usr, token)
#     if verified:
#         usr.is_active = True
#         usr.save()
#         return HttpResponseRedirect('/')
#     else:
#         return HttpResponse("Invalid Verification Link")

Clientapp/templates/clientapp/adminReport.html
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="/static/images/favicon_1.ico">
    <title>Bulk WhatsApp API</title>
    <link rel="stylesheet" type="text/css" media="screen" href="/static/css/bootstrap.min.css"/>
</head>
<body>
<br>
<section class="container">
<div class="row">
    <div class="container well">
      <table class="table">
<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
			<table id="datatable-buttons" class="table table-hover">
			    <thead>
			    <tr>
			        <th>Contact Number</th>
			        <th>Campaign Name</th>
			        <th>Message Text</th>
			        <th>Added On</th>
			        <th>Status</th>
			    </tr>
			    </thead>
			    <tbody>
		    	{% for msg in  individual_messages %}
		    	<tr>
			    	<td>{{msg.to_number}}</td>
                    <td>{{msg.message_format.name}}</td>
                    <td>{{msg.message_format.message_text}}</td>
                    <td>{{msg.added_on}}</td>
                    <td>{% if msg.delivery_status > 0  %}<i class="fa fa-check-circle text-success"></i>{%else %} <b>Pending</b> {% endif %}</td>
			    </tr>	
		    	{% endfor %}
			   </tbody>
			</table>
		</div>
	</div>
</div>
</html>

Clientapp/templates/clientapp/contactus.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/switchery/css/switchery.min.css' %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/bootstrap-select/css/bootstrap-select.min.css' %}"/>
        <link rel="stylesheet" type="text/css" media="screen" href="{% static 'plugins/morris/morris.css' %}"/>
        <script src="{% static 'js/jquery.min.js' %}" ></script>
{% endblock css %}

{% block content %}
<div class="container">
            <!-- Page-Title -->
  <div class="row">
    <div class="col-sm-12">
      <div class="card-box">     
      {% if errors %}
      <div class="col-sm-12">
        <h1 class="text-danger card-box"> {{errors}} </h1>
      </div>
      {% else %}
      <h4 class="m-t-0 header-title"><b>Contacts</b></h4>
      <br>
        <div class="row">
          <div class="col-md-8">
            <form method="POST" class="form-horizontal" data-parsley-validate novalidate>  
            {% csrf_token %}
              <div class="form-group">
                  <label class="col-md-2 control-label" for="id_name"><b>Name</b></label>
                  <div class="col-md-6">
                    <input class="form-control" id="id_name" name="name" type="text" maxlength="100" required placeholder="Enter your full Name here..">
                  </div>                           
              </div>
              <div class="form-group">
                  <label class="col-md-2 control-label" for="id_contact_number"><b>Mobile Number</b></label>
                  <div class="col-md-6">
                    <input class="form-control" id="id_contact_number" name="contact_number" type="Number" maxlength="14" placeholder="Enter Contact Number here..">
                  </div>                           
              </div>
              <div class="form-group">
                  <label class="col-md-2 control-label" for="id_email_address"><b>Email Adress</b></label>
                  <div class="col-md-6">
                    <input type="Email" name="email_address" smaxlength="100" required placeholder="Enter Email Adress here.." class="form-control"
                     id="id_email_address">
                  </div>                           
              </div>
              <div class="form-group">
                  <label class="col-md-2 control-label" for="id_text_message">Message</label>
                  <div class="col-md-6">
                      <textarea type="text" class="form-control" id="id_text_message" name="text_message" rows="4" cols="20" required maxlength="200" placeholder="Enter your text in 200 words">
                      </textarea>
                  </div>
              </div>
              	<button class="btn btn-dark btn-lg waves-effect waves-light" type="submit" name="submit">Submit</button> 
              </form>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    </div>
{% endblock content %}
{% block javascript %}
      <script type="text/javascript" src="{% static 'plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/switchery/js/switchery.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/multiselect/js/jquery.multi-select.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/jquery-quicksearch/jquery.quicksearch.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/select2/js/select2.min.js' %}" ></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>

      <script type="text/javascript" src="{% static 'plugins/autocomplete/jquery.mockjax.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/autocomplete/jquery.autocomplete.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'plugins/autocomplete/countries.js' %}"></script>
      <script type="text/javascript" src="{% static 'pages/autocomplete.js' %}"></script>

      <script type="text/javascript" src="{% static 'pages/jquery.form-advanced.init.js' %}"></script>

      
      <script type="text/javascript" src="{% static 'plugins/parsleyjs/parsley.min.js' %}"></script>  
      <script type="text/javascript">
        $(document).ready(function() {
          $('form').parsley();
        });
      </script>
{% endblock javascript %}

Clientapp/templates/clientapp/report.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    <title>Bulk Whatsapp Report</title>
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/datatables/buttons.bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/datatables/responsive.bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/datatables/dataTables.bootstrap.min.css' %}"/>
        
{% endblock css %}


{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
            <table id="datatable-buttons" class="table table-hover">
                <thead>
                <tr>
                    <th>Contact Number</th>
                    <th>Message Add Time</th>
                    <th>Message ID</th>
                    <th>Delivery Status</th>
                    <th>Delivery Status</th>
                    <th>Send Using</th>
                </tr>
                </thead>
                <tbody>
                {% for msg in  individual_messages %}
                <tr>
                    <td>{{msg.to_number}}</td>
                    <td>{{msg.added_on}}</td>
                    <td>{{msg.whatsapp_message_id}}</td>
                    <td>{% if msg.delivery_status > 0 %}<i class="fa fa-check-circle text-success"></i>{%else %}<i class="fa fa-exclamation-circle"></i> {% endif %}</td>
                    <td>{{msg.delivery_time}}</td>
                    <td>{{msg.sent_using}}</td>

                </tr>   
                {% endfor %}
               </tbody>
            </table>
        </div>
    </div>
</div>
</html>
{% endblock %}
{% block javascript %}
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.js' %}"></script>

    <script src="{% static 'plugins/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.bootstrap.min.js' %}"></script>
    
    <script src="{% static 'plugins/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/buttons.print.min.js' %}"></script>
    
    <script src="{% static 'plugins/datatables/responsive.bootstrap.min.js' %}"></script>
    
    <script src="{% static 'plugins/datatables/moment.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/datetime-moment.js' %}"></script>
    
    <script src="{% static 'pages/datatables.init.js' %}"></script>

    <script type="text/javascript">
    TableManageButtons.init();
    </script>
{% endblock javascript %}

Clientapp/templates/clientapp/whatsapp.html
<!DOCTYPE html>
<html>
<head>
	<link rel="shortcut icon" href="/static/images/favicon_1.ico">
    <title>Bulk WhatsApp API</title>
    <link rel="stylesheet" type="text/css" media="screen" href="/static/css/bootstrap.min.css"/>
</head>
<body>
<br>
<section class="container">
<div class="row">
	<div class="text-center well">	
		<h4 id="connection_status_btn" class="btn btn-danger">Disconnected</h4>	
	</div>
	<div class="container well">
	  <table class="table">
	    <thead>
	      <tr>
	        <th>Status</th>
	        <th>ID</th>
	        <th>User</th>
	        <th>Campaign Name</th>
	        <th>Added On</th>
	        <th>To</th>
	        <th>Message Text</th>
	      </tr>
	    </thead>
	    <tbody>
	    {% for msg_format in msg_formats %}
	    <tr>
	      	<td>Not sent</td>
	      	<td>{{msg_format.id}}</td>
	      	<td>{{msg_format.message_format.from_user}}</td>
	      	<td>{{msg_format.message_format.campaign_name}}</td>
	      	<td>{{msg_format.added_on}}</td>
	      	<td>{{msg_format.to_contact}}</td>
	      	<td>{{msg_format.message_format.msg_text}}</td>
		</tr>
	    {% endfor %}
	    </tbody>
	  </table>
	</div>
</div>
</section>

<script src="/static/js/jquery.min.js" ></script>
<script src="/static/js/bootstrap.min.js" ></script>
<script src="/static/js/main.js" ></script>

</body>
</html>

Clientapp/templates/clientapp/whatsapp_message.html
<!DOCTYPE ht---ml>
<html>
<head>
	<link rel="shortcut icon" href="/static/images/favicon_1.ico">
    <title>Bulk WhatsApp API</title>
    <link rel="stylesheet" type="text/css" media="screen" href="/static/css/bootstrap.min.css"/>
</head>
<body>
<br>
<section class="container">
<div class="row">
	<div class="text-center well">	
		<h4 id="connection_status_btn" class="btn btn-danger">Not Connected</h4>	
		<h4 id="send_message_btn" class="btn btn-primary hidden">Send Messages</h4>
		<h4 id="reject_message_btn" class="btn btn-danger hidden">Reject Messages</h4>	
	</div>
	<div class="well row">
		<div class="col-md-4">
		{% for msg in message_format.whatsapp_text_set.all %}
			<p>{{msg.text}}</p>
		{% endfor%}
		</div>
		{% for msg in message_format.whatsapp_image_set.all %}
			<div class="col-md-4 container"><img class="img-rounded" width="352" height="240" src="{{msg.image.url}}" ></div>
		{% endfor%}
	</div>
	<div class="container well">
	 <table class="table">
	    <thead>
	      <tr>
	        <th>Status</th>
	        <th>ID</th>
	        <th>User</th>
	        <th>Campaign Name</th>
	        <th>Added On</th>
	        <th>To </th>
	      </tr>
	    </thead>
	    <tbody>
	    {% for message in messages %}
	    <tr>
	      	<td>Not sent</td>
	      	<td>{{message.id}}</td>
	      	<td>{{message.message_format.user}}</td>
	      	<td>
	      		{{message.text_delivery.message_text.text}}
	      		{% if message.image_delivery.message_image.image %} <img width="36" height="24" src="{{message.image_delivery.message_image.image.url}}" >{% endif %}
	      	</td>
	      	<td>{{message.added_on}}</td>
	      	<td>{{message.to_number}}</td>
		</tr>
	    {% endfor %}
	    </tbody>
	    <tfoot>
	    	
	    </tfoot>
	  </table>
	</div>
</div>
</section>

<script src="/static/js/jquery.min.js" ></script>
<script src="/static/js/Queue.js" ></script>
<script src="/static/js/bootstrap.min.js" ></script>
<script src="/static/js/main.js" ></script>
<script>
$(document).ready( function() {
	websup.send_message_btn.onclick = websup.message_manager;
	websup.reject_message_btn.onclick = websup.reject_messages ;  
});
</script>
</body>
</html>